#!/usr/bin/env tsx
// Bootstrap cc-web auth:
//   - Generate TOTP secret + cookie HMAC key + 5 recovery codes
//   - Write secrets to ~/.config/cc-web.env (mode 600)
//   - Write recovery code hashes + zero replay counter to data/ (mode 600)
//   - Print QR + plaintext secret + plaintext recovery codes to stdout
//
// Run with: `npm run setup` (from web/). Refuses to clobber an existing
// env file unless --force is passed.

import { authenticator } from "otplib";
import bcrypt from "bcryptjs";
import qrcode from "qrcode-terminal";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

// Run from web/ (via `npm run setup`); data/ is one directory up.
const ENV_FILE = path.resolve(process.env.HOME!, ".config/cc-web.env");
const DATA_DIR = path.resolve(process.cwd(), "..", "data");
const RECOVERY_FILE = path.join(DATA_DIR, "recovery.json");
const AUTH_STATE_FILE = path.join(DATA_DIR, "auth-state.json");

const ISSUER = "cc-web";
const ACCOUNT = "liharr@ai-native";
const RECOVERY_COUNT = 5;
// A-Z + 2-9, excluding ambiguous 0/O/1/I/L. 30 chars → ~5 bits each, 60 bits total per code.
const ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
const BCRYPT_ROUNDS = 12;

function randomCodeChar(): string {
  // Rejection-sample to avoid modulo bias.
  while (true) {
    const b = crypto.randomBytes(1)[0];
    if (b < 256 - (256 % ALPHABET.length)) return ALPHABET[b % ALPHABET.length];
  }
}

function generateRecoveryCode(): string {
  const chars = Array.from({ length: 12 }, randomCodeChar).join("");
  return `${chars.slice(0, 4)}-${chars.slice(4, 8)}-${chars.slice(8, 12)}`;
}

function normalize(code: string): string {
  return code.toUpperCase().replace(/[\s-]/g, "");
}

async function fileExists(p: string): Promise<boolean> {
  try { await fs.access(p); return true; } catch { return false; }
}

async function main(): Promise<void> {
  const force = process.argv.includes("--force");
  if (await fileExists(ENV_FILE) && !force) {
    console.error(`Refusing to overwrite ${ENV_FILE}. Re-run with --force to regenerate.`);
    console.error("(Regeneration invalidates your current TOTP entry and all recovery codes.)");
    process.exit(1);
  }

  const totpSecret = authenticator.generateSecret(20); // 32 base32 chars
  const cookieKey = crypto.randomBytes(32).toString("hex"); // 64 hex chars

  const codes = Array.from({ length: RECOVERY_COUNT }, generateRecoveryCode);
  const hashes = await Promise.all(codes.map((c) => bcrypt.hash(normalize(c), BCRYPT_ROUNDS)));

  const otpauthUri = authenticator.keyuri(ACCOUNT, ISSUER, totpSecret);

  // Print first, persist second — if the user Ctrl-Cs we haven't half-installed.
  console.log("\n cc-web bootstrap\n " + "─".repeat(50));
  console.log("\n  Scan with Microsoft Authenticator (add as 'Other account'):\n");
  await new Promise<void>((resolve) => qrcode.generate(otpauthUri, { small: true }, (qr: string) => {
    process.stdout.write(qr.split("\n").map((l) => "    " + l).join("\n") + "\n");
    resolve();
  }));
  console.log("  If you can't scan, enter the secret manually:");
  console.log("    " + totpSecret);
  console.log("\n  Recovery codes (each usable ONCE if you lose your phone):");
  for (const c of codes) console.log("    " + c);
  console.log("\n  Save into a password manager:");
  console.log("    - The secret above (so a new phone can re-add the account without burning a code)");
  console.log("    - All " + RECOVERY_COUNT + " recovery codes");
  console.log("    - The otpauth:// URI itself, optionally:");
  console.log("      " + otpauthUri);
  console.log("\n  This output won't be shown again.");

  const rl = readline.createInterface({ input, output });
  await rl.question("\n  Press Enter when you've saved everything... ");
  rl.close();

  await fs.mkdir(path.dirname(ENV_FILE), { recursive: true, mode: 0o700 });
  await fs.writeFile(
    ENV_FILE,
    [
      "# cc-web secrets. mode 600. Generated by scripts/setup.ts.",
      "# Regenerate by re-running `npm run setup --force` — this invalidates",
      "# the current TOTP entry and all recovery codes.",
      `CC_WEB_TOTP_SECRET=${totpSecret}`,
      `CC_WEB_COOKIE_KEY=${cookieKey}`,
      "",
    ].join("\n"),
    { mode: 0o600 },
  );

  await fs.mkdir(DATA_DIR, { recursive: true, mode: 0o700 });
  await fs.writeFile(
    RECOVERY_FILE,
    JSON.stringify({ codes: hashes.map((h) => ({ hash: h, usedAt: null })) }, null, 2),
    { mode: 0o600 },
  );
  await fs.writeFile(
    AUTH_STATE_FILE,
    JSON.stringify({ lastUsedCounter: 0 }, null, 2),
    { mode: 0o600 },
  );

  console.log("\n  Wrote " + ENV_FILE);
  console.log("  Wrote " + RECOVERY_FILE);
  console.log("  Wrote " + AUTH_STATE_FILE);
  console.log("\n  Next: systemctl --user restart cc-web.service");
  console.log("        then open https://ai-native.japaneast.cloudapp.azure.com/cc-web/\n");
}

main().catch((e) => {
  console.error("bootstrap failed:", e);
  process.exit(1);
});
